server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 10000
      max-lifetime: 300000




  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${gmail_username}
    password: ${gmail_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

jwt:
  secret: ${jwt_secret}
  accessExpiration: 900          # 15 minutes (recommended)
  refreshExpiration: 604800      # 7 days (recommended)


logging:
  level:
    com.cryo.auth: DEBUG
    org.springframework.security: INFO

# Google Auth Config
google:
  client:
    id: 16297075692-2uar3dbej444u4magvsrfp31n0n0eiho.apps.googleusercontent.com


# //these lines should  remove please rememeber Gopala.
springdoc:
  api-docs:
    path: /auth/v3/api-docs

